services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_sm
    restart: unless-stopped
    environment:
      POSTGRES_DB: SMDB
      POSTGRES_USER: vira
      POSTGRES_PASSWORD: vira
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: